### ISSUE TITLE
请问有演讲的录制视频吗？

### ISSUE THREAD

**Issue by yyicc1108** [Xi-L/PSL-MOBO#1]
hi,

我在《进化优化与机器学习》公众号上关注了这个项目的工作，自己非常感兴趣。

注意到公众号中提到有当时分享的zoom链接，我想问下林博士是否可以分享一下？

非常期待您的回复！

李田洋
东北大学

**Comment by Xi-L** [comment]
你好，

《进化优化与机器学习》公众号上提到的报告，应该指的是我在ICDM2022的[EDMML 2022 Workshop](https://yingbi92.github.io/EDMML_2022/#home)上的invited talk。这个报告没有录制视频。

但是，在这个报告的基础上，我在2023年1月的NICE Seminar上分享了一个更详细的中文演讲（视频见[这里](https://www.bilibili.com/video/BV1Gx4y1G7BC/?spm_id_from=333.999.0.0&vd_source=cdcd9da81c60d8e22defa3782fc35529)）。希望报告的内容对你有用。

祝科研顺利，

林熙
